name: messenger_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  path_provider:
  font_awesome_flutter: ^10.8.0

  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  supabase_flutter: ^2.8.1
  flutter_launcher_icons: ^0.14.3
  mailer: ^6.4.1
  device_info_plus: ^10.1.2
  http: ^1.3.0

  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  page_transition: ^2.2.1
  hive_flutter: ^1.1.0

  crypto: ^3.0.6
  video_player: ^2.9.5
  chewie: ^1.11.3
  camera: ^0.11.1
  cached_network_image: ^3.4.1
  image: ^4.2.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.4
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.2.0
  permission_handler: ^12.0.0+1
  get_it: ^9.2.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/aeck_logo.png"




dependency_overrides:
  floating:
    path: ./android/local_plugins/floating
  vibration: ^3.1.3
  permission_handler: ^12.0.0+1
  flutter_web_auth_2: ^4.1.0

  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner:
  hive_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/sticker/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
